### ISSUE TITLE
Navbar blur not showing on Firefox 101.0

### ISSUE THREAD

**Issue by ZirixCZ** [mark-escosura/my-personal-portfolio#3]
Expected behavior: Navbar background blurrred on scroll
Actual behavior: Navbar background is not blurred.

**Comment by mark-escosura** [comment]
Seems like you're using Firefox as your browser? 

To change preferences in Firefox, visit `about:config`.

Search and set the preferences to the following:
-  `layout.css.backdrop-filter.enabled` preferences (needs to be set to `true`) 
-  `gfx.webrender.all` preferences (needs to be set to `true`)

Let me know if this fixes it 😁


Source: [link](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#:~:text=From%20version%2070%3A%20this%20feature%20is%20behind%20thelayout.css.backdrop%2Dfilter.enabled%20preferences%20(needs%20to%20be%20set%20to%20true)%20and%20the%20gfx.webrender.all%20preferences%20(needs%20to%20be%20set%20to%20true).%20To%20change%20preferences%20in%20Firefox%2C%20visit%20about%3Aconfig.)

**Comment by ZirixCZ** [comment]
Thank you, this fixed the problem. Closing.
